version: 2

build:
  os: ubuntu-22.04
  apt_packages:
    - libportaudio2
  tools:
    python: "mambaforge-22.9"

conda:
  environment: docs/environment.yml

sphinx:
  configuration: docs/source/conf.py
